### ISSUE TITLE
Errors in docs

### ISSUE THREAD

**Issue by RZED786** [DynamicSquid/Night#14]
You say in the docs that there is some support for loops, arrays and assignment operators (is that what they're called?) which the readme says there isn't. Also, the readme has an error. In the if-else if-else bit I think there is meant to be "\n" at the end of the print statements.

**Comment by DynamicSquid** [comment]
Oh, thanks for reading the website! I actually wrote the website according to what my language will look like in the future. Cause right now, it has this ugly long domain name, and it's not really done yet and i didnt expect anyone to use it. But once i get a shorter domain name, and finish the website, then everything will match up.

I also fixed the example. Thanks for noticing!
