### ISSUE TITLE
I found a problem

### ISSUE THREAD

**Issue by johnstev111** [DynamicSquid/Night#17]
Uh so, I was testing  night for the first time, and I was doing something with an if and Woops! an error that sdhouldn't exist.
![image](https://user-images.githubusercontent.com/33234914/90373528-f122d080-e069-11ea-911b-7bb87328b117.png)
I did put a semicolon, weird.
Tip: add the bitwise XOR operator `^`

**Comment by johnstev111** [comment]
I thought I might add the tip anyway just to help you :)

**Comment by RZED786** [comment]
I have this issue too. :/

**Comment by johnstev111** [comment]
I haven't tried defining functions, it probably wayyy too buggy to do that now, so move it to an alpha, Lord Squid

**Comment by RZED786** [comment]
Actually I just forgot to specify the type nevermind.

**Comment by johnstev111** [comment]
Well that works then

**Comment by RZED786** [comment]
I'm looking through the parser code and I might be getting onto something

**Comment by DynamicSquid** [comment]
Oh thanks guys! No semicolom after if statement though. Its just like C syntax. Curly brackets dont have semicolons.

**Comment by DynamicSquid** [comment]
Im still working on better error messages though. Its hard to do the line number. Did you guys find any oher bugs?

**Comment by RZED786** [comment]
With and without semicolons it doesn't work...

**Comment by RZED786** [comment]
Also in parser.h when evaluating if statements it passes the condition to ExtractLine which as far as I can tell is meant for statements with curly brackets.

**Comment by DynamicSquid** [comment]
Okay I fixed it, the if statements should work now. Also, thanks for noticing that! Here's how it works

```cpp
// if statement condition
std::vector<Token> expression(tokens.begin() + 2, tokens.begin() + closeBracketIndex);

try {
        // make the first token the if statement condition
	tokens[2] = EvaluateExpression(expression, variables, functions);
}
catch(const Error& e) {
	int changeSize = tokens.size() - expression.size() - 3;
	throw Error(e.error, tokens, e.start + 2 + changeSize, e.end + 2 + changeSize, e.desc);
}

// erase all the other parameters so we only have one left
tokens.erase(tokens.begin() + 3, tokens.begin() + closeBracketIndex);

// pass the rest of the if statement code into the ExtractLine funciton
ExtractLine(tokens, 5);
```

```
0 1 2   3 4 5
if ( true)  {  }
```

So the only the if statement code gets passed to the function, not the condition

**Comment by RZED786** [comment]
Have you implemented brackets to change order of operations because when I used them it gave me an error. If you haven't implemented it then that's fine, but if you have then there may be a bug.

**Comment by DynamicSquid** [comment]
Where are you using brackets? In functions parameters, variable assignment...

**Comment by RZED786** [comment]
something like:
if(true && (true || false)) {
    print("Hello, world!");
}

**Comment by DynamicSquid** [comment]
Oh yes that. I actually fixed that, but that's going to be in `v2.1`, which is an update all about expressions. Hopefully all the bugs around expressions will be fixed and there will be some fixes around functions as well and new features with expressions. It'll be out by the end of this week maybe?? I'll also properly link it to the ide in the website and update everything

**Comment by johnstev111** [comment]
Oh, ok :)
Also, I noticed you're working on a #include-like statement, but I would suggest to not do a pre-processor, but that of course is the easy option, to just replace the include statement with the source of the header it's including. Just a suggestion =)

**Comment by DynamicSquid** [comment]
Yeah, I'm still thinking about it though
