### ISSUE TITLE
\n doesn't work

### ISSUE THREAD

**Issue by RZED786** [DynamicSquid/Night#19]
When in a function and I try to print something including `\n` it prints `\n` instead of a newline. Also, a character whose value is `' '`, `'\n'` or `'\0'` (perhaps others as well) it disappears. Code: `print("Hello world" + '\n');`
Result:
```
Error - expression is invalid

"Hello world" + 
              ~ 
expected value after operator '+'

**Comment by DynamicSquid** [comment]
Oh interesting. The way it works is the input is a string, so it sees `\n` as a string, not a character. Thanks for bringing that up, I'll try to work on it. You could always just leave that as a string for the meantime

**Comment by RZED786** [comment]
Ok, thanks
