### ISSUE TITLE
Interested in writing a package manager?

### ISSUE THREAD

**Issue by firefish111** [DynamicSquid/night#25]
I was thinking on calling it twilight or dusk, which do you think?
Also for the package manager should I go for a normal C program piggybacking on libcurl or a node.js script for getting data from the cdn?

**Comment by johnstev111** [comment]
``

**Comment by DynamicSquid** [comment]
Hmm... I'm not really fond of changing the name. Also for the package manager, I've never really played around with one before, so I have no clue how it works. Could you explain more about what the package manager will do?

**Comment by johnstev111** [comment]
Well, just take raw night source code from the CDN and plonk it into a folder that the compiler uses the import statement to know 
which modules in the directory to import.
If you want me to do it, I'm thinking of writing it in Go...

**Comment by DynamicSquid** [comment]
huh?

**Comment by johnstev111** [comment]
~~Alright, you probably won't see this message because you just fell asleep and I just woke up. Érd.~~
Alright, I'm making the thing. It's 8am for me now, expect it to be almost done by the time you read this. (~4pm my time)
I'm calling it dusk, because it's before a night, and you need to install packages before you can do anything with them in your Night script. I can rename it, but it has to be short otherwise your "customer" for the lack of a better word, might just not use it because they don't want to type `nightpkg` over and over again, because it's too long (just an example). Like `npm`. short, easy to remember, easy to type a lot. `npm i express`  are probably the first thing a newbie to node types, because express is the most common server library in existence. (I am aware this is a bit long, so I'll cut it short here... we can talk later)

**Comment by johnstev111** [comment]
Alright, it's very simple, BUT IT WORKS. check out https://github.com/johnstev111/dusk/

**Comment by DynamicSquid** [comment]
okay but you still haven't told me what this package manager does

**Comment by johnstev111** [comment]
> Well, just take raw night source code from the CDN and plonk it into a folder that the compiler uses the import statement to know
which modules in the directory to import.

I have

**Comment by DynamicSquid** [comment]
no clue what that means.... cdn? import statement?

**Comment by johnstev111** [comment]
CDN means Content Delivery Network, like jsdelivr. Some server that hosts a bunch of code. The import statement. Like python, you see
```py
import time
import Flask
import tkinter
```
those are import statements. They are statements, that import.

**Comment by johnstev111** [comment]
So, it means that when you  type, for example in night `use lalala;` (don't have to use that syntax, but there isn't one currently so I made one up) the compiler would say take the pre-processor and replace that `use lalala;` with the contents of `./dusk_modules/lalala.night`. It's a bit complex, I know, but just bear with me.

**Comment by DynamicSquid** [comment]
why would I need a package manager though?

**Comment by johnstev111** [comment]
you said you wanted some sort of a `#include`-like statement.... I was helping you.... like python doesn't have all those packages baked in one binary, they're stored on PyPI, the Python Package Index, which is basically a fancy CDN.

**Comment by DynamicSquid** [comment]
OHHHHH is that why python has so packages? I was thinking of just putting everything into one binary, but I guess I could have different packages...

**Comment by DynamicSquid** [comment]
so the `dusk_modules` folder, that's where I write all my packages?

**Comment by johnstev111** [comment]
Er... no, you plop them on the CDN. The dusk_modules directory is where the modules are installed locally. The cdn is hosted on repl.it, I'll invite you now (it's called `duskcdn`)

**Comment by AntimatterReactor** [comment]
well, have just seen this, it's an interesting idea tbh

**Comment by AntimatterReactor** [comment]
i have look at the code... i... i realize i don't know how to code in go-lang
and... not to be an asshole here, i just... i don't think i can contribute to dpm (dusk package manager, i mean...)...

**Comment by Lethdev2019** [comment]
@AntimatterReactor @DynamicSquid @johnstev111 
Can i help. I can create a command line tool for you like npmg.exe --install [package_name] BUT we need to make a repository for that using an index server for github releases.

**Comment by DynamicSquid** [comment]
Uh sure I guess! I was talking with jonstev and we made a plan that we'd have two repositories, Night, and the External code, and use MinGW to compile them both, so they can be run fairly easily. I'm not really sure though @johnstev111 has more information. I'm actually really clueless on this kind of stuff

**Comment by Lethdev2019** [comment]
@DynamicSquid ok - i invited you to the repl

**Comment by johnstev111** [comment]
@DynamicSquid Squod, look. Lethdev can't compile python into ELF binaries that easily, and remember CROSS PLATFROM, and this needs to be a binary, so I woud've done node, that's why I chose Golang. As simple as that.
No scripting, and also, was literally half-way through adding to it, if you wanna help, I mean ~~Golang only took 5 hours to learn~~

**Comment by Lethdev2019** [comment]
@johnstev111 @DynamicSquid WELL NOW I CAN'T BECAUSE ALL THE CODE IS MAGICALLY MISSING.

**Comment by johnstev111** [comment]
well what happened, i can recover it

**Comment by DynamicSquid** [comment]
uhhh no clue what's going on, but yeah sure I guess I'll go with johnstev

**Comment by DynamicSquid** [comment]
lol I love that quote "magically missing"

**Comment by firefish111** [comment]
Working build of dusk running on mingw
![image](https://user-images.githubusercontent.com/33234914/93012883-a7ab9f80-f59b-11ea-9fd8-cec5188c8296.png)

**Comment by Lethdev2019** [comment]
ooh nice

**Comment by Lethdev2019** [comment]
meet you on the slice lang

**Comment by Lethdev2019** [comment]
You will need to add it to releases though on your repo

**Comment by firefish111** [comment]
It's not done YET
still need a version tracker, like a working package-lock.json

**Comment by Lethdev2019** [comment]
@firefish111 
That is not too hard - we can use the metadata to get current version and the latest version then compare them.
also, i am on Dusk again.

**Comment by firefish111** [comment]
@Lethdev2019 @DynamicSquid @AntimatterReactor I think we're done; check the release and test it (hopefully works, included windows binary and linux binary that works on repl.it)

**Comment by Lethdev2019** [comment]
@firefish111 your cdn is down

**Comment by firefish111** [comment]
@Lethdev2019 I KNOW, IT'S BLASTED BROKEN, been stressing over it for the past day

**Comment by Lethdev2019** [comment]
@firefish111 @DynamicSquid we need dusk to be able to have dependencies - it means adding import to night too.

**Comment by firefish111** [comment]
@Lethdev2019 that's the point, we have a use statement to import dusk packages, and an import statement to import local files

**Comment by DynamicSquid** [comment]
@firefish111 @Lethdev2019 You guys know what this means...

![Screenshot (243)_LI](https://user-images.githubusercontent.com/60247838/95690377-88248880-0bd4-11eb-9f69-0f59b70a0356.jpg)

**Comment by DynamicSquid** [comment]
ahhh... finally, time to take a break

**Comment by DynamicSquid** [comment]
okay time to do package manager. wait why can't we just use npm? I guess it's more fun to create things ourselves... or is it in this case??? cause have you seen the npm website??? it's so cool!

**Comment by firefish111** [comment]
@DynamicSquid (What? I'm just uploading night packages to npm, a cdn for JAVASCRIPT code, *grilling apricots on the brabecue*)

**Comment by DynamicSquid** [comment]
no I kinda want to make a packager manager ourselves. the package manger you have rn is really good lets use that one

**Comment by DynamicSquid** [comment]
also why would you grill apricots on a barbecue

**Comment by firefish111** [comment]
@DynamicSquid ~~do you not understand sarcasm~~ Alright then, would you like to help add search to dusk? I mean it only takes 5-6 hours to learn...

~~~
also this is a codeblock
made of three tildes
instead of three backticks
~~~

**Comment by DynamicSquid** [comment]
Not, it can take like 1 or 2 hours wihtllth Ctrl + C and Ctrl + V and stackoverflow

**Comment by firefish111** [comment]
@DynamicSquid Quite right, but I'll invite you to dusk. ~~(oh christ it's a private repl, my hacker expired, gonna have to make it public)~~

**Comment by DynamicSquid** [comment]
I'm already invited to dusk...

**Comment by DynamicSquid** [comment]
Wait, why don't we link the exe file for Night for convenience again?

**Comment by DynamicSquid** [comment]
@firefish111 Wait, but that's how how things work. All the other repositories ask you to build this from source, so the user needs Go installed?

Wait no OH!!! So the GitHub page tells the user how to build from source, but the website has the `exe` files already there!! k I'll update some stuff I'm a genius

**Comment by firefish111** [comment]
@DynamicSquid What the hell I'm not up at 1am or 1am, (haha daylight savings joke lol, oh wait you won't find it funny because in the US donno about Canada they change in a week)

**Comment by CodeLongAndProsper90** [comment]
Yeah btw, could we perhaps move this to gitlab? It's a bit of a better ecosystem.

**Comment by CodeLongAndProsper90** [comment]
Or mirror gitlab here

**Comment by DynamicSquid** [comment]
@CodeLongAndProsper90 but gitlab's lesser used isn't it?

**Comment by CodeLongAndProsper90** [comment]
Yeah but Gitlab doesn't take a repo offline since it can be used to download YouTube videos

**Comment by CodeLongAndProsper90** [comment]
And gitlab has great ci

**Comment by DynamicSquid** [comment]
~~let's create our own version of github~~ But I'm so used to Github. I guess I can try Gitlab after I release `v3.2` (which I'm working on rn, releasing in a couple hours)

**Comment by CodeLongAndProsper90** [comment]
Well I can fork it and set it up on Lab…

**Comment by DynamicSquid** [comment]
Yeah I was gonna do that. But give me a while, I really want to get v3.2 out asap

**Comment by firefish111** [comment]
@DynamicSquid Lol you didn't merge the pr, did you hit le wrong button

**Comment by DynamicSquid** [comment]
@firefish111 ik, that's because your pr wouldn't work. Don't worry though, the preprocessor works now. All I need to do is to test it with Dusk and we're good!

**Comment by firefish111** [comment]
@DynamicSquid Aight then, yh ik the pr is le brokuenu, just oki put it in aight. (lol daylight savings is making it sooooo dark, it went back this morning for the UK, unlike you which is on the 1st)

**Comment by DynamicSquid** [comment]
lol!

**Comment by firefish111** [comment]
@DynamicSquid It's only 5:20pm and it is already dusk, hehe pun intended

**Comment by firefish111** [comment]
Also why is le @CodeLongAndProsper90 sticking his nose in everything

**Comment by DynamicSquid** [comment]
@firefish111 wdym? I like codelong

**Comment by firefish111** [comment]
@DynamicSquid Yeah but his like imposing GitLab and like... you know have heard bad things abut it, and really GitLab is scarcely used, but Github - although owned by le macrohard - is mor3e popular, and better, (and isn't gitlab also owned by le macrohard?)/

**Comment by CodeLongAndProsper90** [comment]
No gitlab isn't owned by M$

**Comment by CodeLongAndProsper90** [comment]
And given that a tool used to download YouTube videos was taken offline with only a notice from the RIAA, and the complaint was baseless, it's safer to not depend on GitHub

**Comment by firefish111** [comment]
@CodeLongAndProsper90 Well we, after all, are NOT making a video downloader, but instead making a programming language, nothing media-related, that is exposed to copyright

**Comment by DynamicSquid** [comment]
@firefish111, @CodeLongAndProsper90 guys, as programmers, if we don't like something, then we can just make that thing! let's go make github

**Comment by firefish111** [comment]
@DynamicSquid Lol, one `SquidHub` coming right up, the future client for the ahead-of-time git client `squidgit`! (what the hell)

**Comment by CodeLongAndProsper90** [comment]
> Well we, after all, are NOT making a video downloader

If this repo got taken down, which could happen and Squid didn't have a copy of the code, bam there goes Night.

**Comment by CodeLongAndProsper90** [comment]
And we could spin up a server, anyone got some spare cash for server space?

**Comment by DynamicSquid** [comment]
Yeah I'm definitely moving this to Gitlab. Almost done v3.2, just have to work the readme files

**Comment by firefish111** [comment]
@CodeLongAndProsper90 Lol no, I can't even renew my replit hacker plan

**Comment by firefish111** [comment]
@DynamicSquid wait what's your incentive?

**Comment by DynamicSquid** [comment]
@firefish111 my what?

**Comment by firefish111** [comment]
@DynamicSquid your 
![image](https://user-images.githubusercontent.com/33234914/97114569-2b9f8e00-16e9-11eb-8a0e-ec784a409b12.png)

**Comment by DynamicSquid** [comment]
@firefish111 Honestly yes

**Comment by firefish111** [comment]
@DynamicSquid lol what's your incentive to switch to GitLab

**Comment by DynamicSquid** [comment]
wait how does markdown work? if I do this...


  - test
- test

**Comment by DynamicSquid** [comment]
I want to switch to gitlab so night can be everywhere

**Comment by DynamicSquid** [comment]
@firefish111 I have a good idea

**Comment by firefish111** [comment]
@DynamicSquid  yipadee

**Comment by DynamicSquid** [comment]
K, give me 2 minutes, but my plan is basically I'm going to leave a type in the REAMEME file. Fork this repo, fix the type, then create a pull request. Then you'll be listed as one of the contributors
![Screenshot (249)](https://user-images.githubusercontent.com/60247838/97114781-2ece5600-16b8-11eb-9d60-49dd87154cae.png)
!

But don't do it until I say so

**Comment by DynamicSquid** [comment]
@firefish111 K there's a typo in the first sentence "useability" if you want to fix that for me :)

**Comment by firefish111** [comment]
@DynamicSquid lol cheat but oki

**Comment by DynamicSquid** [comment]
looking good over there!

**Comment by CodeLongAndProsper90** [comment]
And GitLab has native CI support unlike GitHub

**Comment by firefish111** [comment]
@CodeLongAndProsper90 Alright, we get it, some service that barely anybody uses is better than the most common one, lol it happens all the time. Take VIM for instance (I use vim, most other people use ***`nano`***, which is the worst pile of .... excrement ever),.

**Comment by CodeLongAndProsper90** [comment]
Ew nano
Spacemacs with Evil FTW

**Comment by firefish111** [comment]
@DynamicSquid lol it says `pks` not `dusk_pkgs`. does this imply you want to change?

**Comment by CodeLongAndProsper90** [comment]
We should call the Debugger `dawn`

**Comment by firefish111** [comment]
@DynamicSquid You know what I was gonna `ORIGINALLY` call dusk? `day`.

**Comment by CodeLongAndProsper90** [comment]
Uh

**Comment by firefish111** [comment]
@CodeLongAndProsper90 ***boom. shattered. ~~uh-oh he found us, take his to the barbecue!~~***

**Comment by DynamicSquid** [comment]
@firefish111 pkgs it is

**Comment by DynamicSquid** [comment]
@firefish111, @CodeLongAndProsper90 do you guys know how to link a exe file with a HTML download button?

**Comment by firefish111** [comment]
@DynamicSquid oki I will modify le dusk to suit

**Comment by firefish111** [comment]
@DynamicSquid You do markdown image with onclick, dat how

**Comment by DynamicSquid** [comment]
@firefish111 I need a link for dusk.exe

**Comment by firefish111** [comment]
Ye, make an html server that does le download, or do you want le exe file? put le exe file in le release, then make le markdown image inside a link to le same link to le release exe. le oki?

**Comment by firefish111** [comment]
@DynamicSquid also what is handeling, it's handling

**Comment by DynamicSquid** [comment]
@firefish111 Wait what no I just need a link to the exe file.

**Comment by firefish111** [comment]
@CodeLongAndProsper90 github better
![image](https://user-images.githubusercontent.com/33234914/97115721-27c33a00-16f0-11eb-9642-c5b1ed295b53.png)

@DynamicSquid for le link you need to OPLOAD LE EXE
![image](https://user-images.githubusercontent.com/33234914/97115734-41fd1800-16f0-11eb-8b64-b9b1a2f4207a.png)

**Comment by DynamicSquid** [comment]
Damn, it crashed my pluggin lol

**Comment by DynamicSquid** [comment]
Okay it worked!

**Comment by DynamicSquid** [comment]
But it keeps telling me that it's a virus could you fix that?

**Comment by firefish111** [comment]
@DynamicSquid lol no, that's your problem, your browser says that "eXe fIlEs mUsT bE mAlIcIoUs" but not always true, I can report it being safe for you ~~also do you use edge~~

**Comment by DynamicSquid** [comment]
@firefish111 i use chrome

**Comment by DynamicSquid** [comment]
https://night-website.dynamicsquid.repl.co/html/dusk.html

**Comment by DynamicSquid** [comment]
@firefish111 How do I combine dusk.exe and night.exe into one exe? Same for the Linux variants?

**Comment by firefish111** [comment]
@DynamicSquid WHAT NO PLOZ DELETE LE LINK, le réal link is le here
[ ] for windows: https://github.com/firefish111/dusk/releases/download/v1.0-alpha/dusk.exe
[ ] for linux: https://github.com/firefish111/dusk/releases/download/v1.0-alpha/dusk
# aha lol for dat i need to use a thing called `CGo`, can you reséarch please?

**Comment by firefish111** [comment]
# lol help me i slow `sed -e 's/dusk_pkgs/pkgs/g' -i dusk.go`

**Comment by firefish111** [comment]
@DynamicSquid have i lost contact, I need you to read my previous massgaes

**Comment by DynamicSquid** [comment]
Don't worry it's all working fine

**Comment by firefish111** [comment]
@DynamicSquid not the right ones, gosh

**Comment by DynamicSquid** [comment]
@firefish111 wait what

**Comment by DynamicSquid** [comment]
@firefish111 well, Imma do that later. time to take a break

**Comment by firefish111** [comment]
@DynamicSquid yes lol let's do
