### ISSUE TITLE
Compiled editions for platforms

### ISSUE THREAD

**Issue by Lethdev2019** [DynamicSquid/Night#27]
some users cannot compile the language due to a package that is not supported or is hard to get... CMake or things like it.
And otherusers just don't know how - because you did not have instructions on how to compile or they don't have permissions (like me :( )  or they could just be getting started programming (it is like downloading discord and they tell you that you have to set it up on your own by playing around with electron for hours **with no instructions**). What i am suggesting is we have the full compiled version in the releases for every major OS (windows (.exe), macos (.app) and linux (elf)) but the source code as well for advanced users.

Continuing with making users set it up on their own **might** deter them from getting it in the first place.

**you do not have to accept this idea.**

**Comment by DynamicSquid** [comment]
Good idea. I'm going to play around with the source build a little more and try and see if there's anything I can do

**Comment by johnstev111** [comment]
Hm... MacOS would be inaccessible, because I don't have a Mac (or any Apple product, for that matter), but maybe Squod does...

**Comment by Lethdev2019** [comment]
@johnstev111 try a virtual machine

**Comment by Lethdev2019** [comment]
@DynamicSquid  @DynamicSquid - if you created a version that could run a script from a path like ```night --run "scripts/script.night"``` i could make you a code editor using electron.

**Comment by johnstev111** [comment]
I don't have a license for it MacOS.... duh

**Comment by Lethdev2019** [comment]
just looked it up some more - getting the license does not matter - the vm would be blocked any ways because of the EULA including that apple must not be run on non-apple devices.

**Comment by Lethdev2019** [comment]
@johnstev111 @DynamicSquid to solve macos - we just compile it to a .app file then put it in a zip.

**Comment by johnstev111** [comment]
How to compile to .app file if nobody here has a fresh copy of MacOS?

**Comment by Lethdev2019** [comment]
Can we talk about this in repl.it in NpMG

**Comment by DynamicSquid** [comment]
Well, if you can't compile the lang, then just use the website :)

**Comment by firefish111** [comment]
Er... one option, but what if you don't have internet, hehe (like why would that happen, but PRETEND IT'S STILL 1996 AND WE ALL HAVE 56K MODEMS)

**Comment by DynamicSquid** [comment]
Okay but if you dont have internet then how did you find this GitHub page in the first place?

**Comment by firefish111** [comment]
I do have internet, the suspension of disbelief

**Comment by DynamicSquid** [comment]
Also im really trying to focus on v3.0 right now, and getting that ready as soon as possible, but once i get that done, then we can probably do all this

**Comment by DynamicSquid** [comment]
Also yeah i dont have mac or linux, so one of you guys have to do it and send me the file

**Comment by firefish111** [comment]
Didn't you install VBox? If you deleted the VM I can help you recover it, I've used virtualbox a lot

**Comment by firefish111** [comment]
You can use th\at for your linux install

**Comment by DynamicSquid** [comment]
Yeah i tried that out but i deleted it since i didnt know how to use linux properly lol.

**Comment by firefish111** [comment]
Wait... repl.it is linux, you do know that?

**Comment by DynamicSquid** [comment]
OHHHH right so I can just compile Night in repl.it, and download the elf file

**Comment by DynamicSquid** [comment]
Wait, how am I going to put the code for the release then? Should I add the source code binary, and the compiled version all into one release?

**Comment by firefish111** [comment]
Well once we've combined the C++ code of Night and the Go code of dusk into one binary, you could but the BINARIES under the release binaries or you could plonk the Makefile in here (time to learn polygott)

**Comment by Lethdev2019** [comment]
> Wait... repl.it is linux, you do know that?

well i certainly do. Mint, Ubuntu and Debian.

**Comment by firefish111** [comment]
@DynamicSquid Here's something: you can actually put compiled executables inside the "Assets" of a release

**Comment by DynamicSquid** [comment]
hi im so happy rn

![Screenshot (240)_LI](https://user-images.githubusercontent.com/60247838/93715757-88c38500-fb28-11ea-8420-4ecc6e48cb5b.jpg)

recursion works!!

**Comment by DynamicSquid** [comment]
been trying for a whole day to get that to work. going to fix up some bugs with that, and i'll test the other code, should be simple since functions are the hardest and everything else is easy, then I'll release v3.0 hopefully today and I'll start work on the package manager you guys made :)

**Comment by DynamicSquid** [comment]
![Screenshot (241)_LI](https://user-images.githubusercontent.com/60247838/93716036-456a1600-fb2a-11ea-961d-fa22dc2a72e3.jpg)

omg guys looks it's the fib sequence yay!!!

**Comment by Lethdev2019** [comment]
PLEASE compile it.

**Comment by Lethdev2019** [comment]
plus doing it on the web is not reliable - blackouts ect. plus it may be faster on the computer due to less requests and people would be able to create games and guis on it which is simply not possible with just a terminal in the browser.

**Comment by firefish111** [comment]
@Lethdev2019 @DynamicSquid @firefish111 GUYS! Use GitHub Actoins
![image](https://user-images.githubusercontent.com/33234914/93795486-5782ac00-fc31-11ea-9de9-527615467e15.png)

**Comment by Lethdev2019** [comment]
how are we gonna add that to releases?

**Comment by firefish111** [comment]
we compile it, download it, it's a good as that
(if we can't download it, then if we can make http requests we might be able to tranfer it off of there with a server) I'm thinking .deb and .rpm time @Lethdev2019 @DynamicSquid

**Comment by DynamicSquid** [comment]
I tried compiling it to a .exe file, and running it on another windows 10 os, but I think you still need gnu installed for it to work

**Comment by DynamicSquid** [comment]
i put the exe file generated using g++ on here if you guys want to try it out

**Comment by Lethdev2019** [comment]
> i put the exe file generated using g++ on here if you guys want to try it out

Where?

**Comment by firefish111** [comment]
@DynamicSquid Is it an asset under the release?

**Comment by DynamicSquid** [comment]
@Lethdev2019 @firefish111 guys it's like right there in the files...

**Comment by AntimatterReactor** [comment]
well, seeing this is a concern, i finally understood that linux and mac, unlike windows **can** run any file format _**directly**_ as an executable. https://askubuntu.com/questions/156392/what-is-the-equivalent-of-an-exe-file, https://stackoverflow.com/questions/4073289/compiling-simple-hello-world-program-on-os-x-via-command-line. Although on mac, that means it's not an app, just an executable.

**Comment by AntimatterReactor** [comment]
see: 
![image](https://user-images.githubusercontent.com/63902100/94523105-e9ef0500-025a-11eb-9646-5d8c9d6233fb.png)?

**Comment by AntimatterReactor** [comment]
yeah, nvm

**Comment by Lethdev2019** [comment]
@DynamicSquid Does not work - librairies are missing for the exe

**Comment by firefish111** [comment]
@DynamicSquid It's good practice to not have it in the files. Put it in the release assets.

**Comment by DynamicSquid** [comment]
Yeah imma naie a release on this pretty soon.Also @Lethdev2019, are you on windows cause it worked for me?

**Comment by Lethdev2019** [comment]
@DynamicSquid oh you did not have instructions on using it at the time.
