### ISSUE TITLE
Missing docs for source build

### ISSUE THREAD

**Issue by CodeLongAndProsper90** [DynamicSquid/Night#31]
In the website there is a tab `Source build` and yet the HTML is empty.
You also appear to have a PE bin in the root, indicating a Windows build.
Do you plan to use Autoconf and Make?

**Comment by DynamicSquid** [comment]
Yeah, haven't really been working on the website lately... also what's a PE bin? And no clue how to use Autoconf and Make...

**Comment by DynamicSquid** [comment]
My plan right now is to just have maybe a `.exe` file and an `.elf` (well once it get it working for linux) file and assume the user has gnu installed. The current exe file is just for testing purposes, and I'll put it in the release once it's done

**Comment by firefish111** [comment]
@DynamicSquid 
PE bin = PE binary = .exe file
elf binaries don't have extensions
and no idea what autoconf is, But try your best to understand the makefile in my pr

**Comment by CodeLongAndProsper90** [comment]
Where is it (the Makefile)?  I don’t see a Pr…

**Comment by firefish111** [comment]
Closed, #28

**Comment by CodeLongAndProsper90** [comment]
Uh I'm not finding that in the repo, `ls -R . | grep Makefile` is empty.

**Comment by firefish111** [comment]
@CodeLongAndProsper90 can you not actually click: 
![image](https://user-images.githubusercontent.com/33234914/94590349-74952b80-027e-11eb-8048-0b7a48b4ad11.png) it leads you to pr #28 JUST CLICK ON IT

**Comment by CodeLongAndProsper90** [comment]
Nevermind, I wrote my own
