### ISSUE TITLE
Give me something to do please

### ISSUE THREAD

**Issue by Lethdev2019** [DynamicSquid/Night#37]
Seriously please... can i do like an IDE for it or something?

**Comment by AntimatterReactor** [comment]
Suggestion: yes, IDE, or vscode syntax, or just watch more youtube

**Comment by DynamicSquid** [comment]
Try walking your dog. That's what I usually do when I get bored.

**Comment by DynamicSquid** [comment]
Jk lol idk. Have you tried to compile and run night using g++ on windows yet?

**Comment by DynamicSquid** [comment]
Help antimatter on his night compile (if that's okay with antimatter)
