### ISSUE TITLE
Bugs? - No semicolon doesn't generate error

### ISSUE THREAD

**Issue by AntimatterReactor** [DynamicSquid/Night#38]
example:
```
print("AAAA\n")
```
once runned, it doesn't do anything, no error message, no result

**Comment by DynamicSquid** [comment]
Yeah for v2.0 better error mags will be implemented so that should be fixed. Thanks for reporting that

**Comment by AntimatterReactor** [comment]
ok...

**Comment by alexapostolu** [comment]
Yup, fixed now!
