### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by CodeLongAndProsper90** [DynamicSquid/Night#41]
For the PKGBUILD, a new release is needed so that the tarball can be fetched, and the repo contains a bugfix allowing code to run, so, perhaps create a v3.0.1 bugfix release. Thanks!

**Comment by DynamicSquid** [comment]
can I release it now?

**Comment by DynamicSquid** [comment]
hmm.. slight problem with the Makefile though. To use the `make` command, you have to be in the same directory as the Makefile, but I want the current directory to be outside the `src` folder so this would be the best option:

```
make -S src
./night source.night
```

Should we change the readme file to say that? Or should we have the Makefile outside the `src` folder?

**Comment by CodeLongAndProsper90** [comment]
The best thing would be a soft link but Windows can’t handle that, perhaps just make a dummy Makefile?
For example
```make
.PHONY: all
all:
make -S src 
```

**Comment by CodeLongAndProsper90** [comment]
Sorry for formatting on mobile rn

**Comment by DynamicSquid** [comment]
Well, im not really an expert in makefiles so im not sure. Would that be better than what we have now?

**Comment by CodeLongAndProsper90** [comment]
I mean cd src && make clean all is pretty standard

**Comment by DynamicSquid** [comment]
Sure i guess
