### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by HahaYes-dev** [DynamicSquid/Night#45]
JDOG and I are wondering if your website is on github, if so, can we make some PRs?
Thanks,
HahaYes

**Comment by DynamicSquid** [comment]
Who's jdog? And no, but you can just make a pr here thatd be fine

**Comment by HahaYes-dev** [comment]
Ah thanks squid, prob be making a few PRs here and there

**Comment by DynamicSquid** [comment]
Oh yeah that'd be great help if you do! I'm not the best at writing descriptive stuff nor web designing...
