### ISSUE TITLE
Continuous Integration?

### ISSUE THREAD

**Issue by DynamicSquid** [DynamicSquid/Night#48]
Hi guys. @firefish111 @CodeLongAndProsper90 

Should we set up some CI? Never done it before so it should be interesting, and it should help with futures PRs

**Comment by CodeLongAndProsper90** [comment]
I think we should add an `assert` statement and the self-host the tests.

**Comment by DynamicSquid** [comment]
`assert` as in `assert(str != null)`? Also how do we self host the tests? Do we create a folder called `tests` and have test code in their?

**Comment by CodeLongAndProsper90** [comment]
No I mean Night is tested in Night.

**Comment by DynamicSquid** [comment]
oh yeah that's what I meant. so we have a file containing test code written in Night, and we test a commit user that. How are we going to get it up though?

**Comment by CodeLongAndProsper90** [comment]
I don’t know.

**Comment by DynamicSquid** [comment]
oh um... I guess we just play around with some stuff until something works?

**Comment by CodeLongAndProsper90** [comment]
Repl uses CircleCI…

**Comment by DynamicSquid** [comment]
Should we give that a try? I'm playing around with the built in github workflows now... no clue what I'm doing though

**Comment by CodeLongAndProsper90** [comment]
Sounds good, I guess...

**Comment by DynamicSquid** [comment]
wait theres 1205 lines of errors on the CI that's more errors as lines of code I think I did something wrong...

**Comment by DynamicSquid** [comment]
update: I switched to CircleCI and got a Linux pipeline working, now I'm trying to do Windows

**Comment by firefish111** [comment]
WHAT THE HELL STOP PINGING ME AT MIDNIGHT @DynamicSquid @CodeLongAndProsper90

**Comment by firefish111** [comment]
@DynamicSquid @CodeLongAndProsper90 Shall we implement the preprocessor as well, under #28 (please click on it codelong, unlike last time, and then you'll get there)

**Comment by DynamicSquid** [comment]
Shouldn't a preprocessor be compiled separately?

**Comment by firefish111** [comment]
No. Look at C. @DynamicSquid The linking is done separately, but since this a scripting language, we don't need to care about that.
The preprocessor does exactly what `#include` does.

Now, @CodeLongAndProsper90 PLEASE CHECK #28 (and click on the text that says #28 this time OK?!?!)

**Comment by DynamicSquid** [comment]
Oh okay. Is there a way where you could create a new PR with the preprocessing cause I can't seem to reopen the old one...

**Comment by firefish111** [comment]
Erm, Yeah oki, just need to do it with night `[3, 0, 1] which will take me about a decade (probably 20 minutes lol)

**Comment by DynamicSquid** [comment]
lol okay. also i'm still testing the CI so if it says your PR failed the tests don't worry about it for now

**Comment by firefish111** [comment]
Try TravisCI, it's more commonly used

**Comment by DynamicSquid** [comment]
Yeah check the reamdme file, I'm already setting it up

**Comment by firefish111** [comment]
One question, how do you get the `night::string` value as a `std::string`?

**Comment by DynamicSquid** [comment]
I only use `std::string` for file handling. Everything else do with `night::string`

**Comment by firefish111** [comment]
yeah but what if I want to add a `night::string` to a `std::stringstream`?

**Comment by DynamicSquid** [comment]
you don't :)

**Comment by DynamicSquid** [comment]
wait, can you share a snippet of the code?

**Comment by firefish111** [comment]
then how to concatenate a `std::string` to a `night::string` then

**Comment by firefish111** [comment]
![image](https://user-images.githubusercontent.com/33234914/94995548-fba41580-0596-11eb-902a-889b4ca9b0cb.png)

**Comment by DynamicSquid** [comment]
I mean... the reason why I created my own data types instead of using the much faster more reliable std is because I actually don't know. If you must use `std::string`, you could do this:

```
night::string str1;
std::string str2;

str1 += str2.c_str();
```

**Comment by DynamicSquid** [comment]
Or vise versa:

```
std::string str1;
night::string str2;

str1 += str2.cstr(); // returns char*
```

**Comment by firefish111** [comment]
Thank you =) been a great help

**Comment by firefish111** [comment]
Also in your MAkefile there is a reference to the env $DESDIR. I don't know what that is, what is it? @DynamicSquid

**Comment by DynamicSquid** [comment]
idk codelong did that. I think it's for dusk

**Comment by firefish111** [comment]
No, it's Destination directory, like `.` basically

**Comment by DynamicSquid** [comment]
oh, idk then. also for the ci, might go with circleci as it gives a better interface. don't really see a difference between that and travis

**Comment by firefish111** [comment]
@DynamicSquid Would GPL3 be better than Apache2? As far as I know it's only one extra feature in GPL called "Same license"

**Comment by CodeLongAndProsper90** [comment]
Typo, it should be $DESTDIR

**Comment by DynamicSquid** [comment]
oh yeah @CodeLongAndProsper90, could you give advice for the license? Should I use the GPL?

**Comment by CodeLongAndProsper90** [comment]
GPL ensures that any code that uses this code is GPL’ed and any forks must have it as well
