### ISSUE TITLE
Bugs(??) - Input is Undefined

### ISSUE THREAD

**Issue by AntimatterReactor** [DynamicSquid/Night#49]
![image](https://user-images.githubusercontent.com/63902100/94980195-97ab2e00-0551-11eb-933b-46a5240debca.png)
![image](https://user-images.githubusercontent.com/63902100/94980198-9aa61e80-0551-11eb-83a6-84d5509f3ce8.png)

**Comment by DynamicSquid** [comment]
lol I forgot to put input in the release!! cause for v3, I completely restarted the code, but I guess i might of missed that. that's why it's in 2.4 but not 3.0!!! might have it 3.1

**Comment by AntimatterReactor** [comment]
ok
