### ISSUE TITLE
About non-coding stuff...?

### ISSUE THREAD

**Issue by AntimatterReactor** [DynamicSquid/Night#61]
EXAMPLE:

- Building better docs?
- Making a github 'Night' team/organisation profile (like a lot of big languages)?
- Github action for main and side project progress tracking?
-  ~~A task list for everyone? TBH I'm bored~~
- etc, etc; that kind of stuff

**Comment by Lethdev2019** [comment]
well Dynamic squid has not accepted the doc concept.

**Comment by DynamicSquid** [comment]
Some help on the docs would be nice :)

**Comment by Lethdev2019** [comment]
@DynamicSquid how?

**Comment by firefish111** [comment]
@AntimatterReactor I made an organisation like about 3 months ago but squid asked me to delete it. He doesn't want me to remake it

**Comment by firefish111** [comment]
@DynamicSquid should i remake the organisation?

**Comment by DynamicSquid** [comment]
No

**Comment by AntimatterReactor** [comment]
Ok, fair enough.
