### ISSUE TITLE
Feature - Suggestion: Logo

### ISSUE THREAD

**Issue by AntimatterReactor** [DynamicSquid/night#67]
I mean, like 65-80% of language have those, so... why not?
But no pressure

**Comment by DynamicSquid** [comment]
A logo? I already have one :) Its on the website

**Comment by AntimatterReactor** [comment]
oh. so what about on the readme?

**Comment by AntimatterReactor** [comment]
oh well, a background gotta go to waste, then
![NightLogoBackground](https://user-images.githubusercontent.com/63902100/98488722-619e4f80-225d-11eb-9dfd-cfe1009a620e.png)
