### ISSUE TITLE
Trouble compiling night

### ISSUE THREAD

**Issue by RowanFromBJC** [DynamicSquid/night#71]
I'm trying to compile night, but I get errors using g++, clang++, and make.
g++ error:
```
In file included from src/../include/night.hpp:3:0,
                 from src/night.cpp:1:
src/../include/token.hpp:203:7: error: ‘variant’ in namespace std’ does not name a template type
  std::variant<
       ^~~~~~~
exit status 1
```
clang++ error:
```
In file included from src/night.cpp:1:
In file included from src/../include/night.hpp:3:
src/../include/token.hpp:203:7: error: no template named 'variant' in namespace
      'std'
        std::variant<
        ~~~~~^
1 error generated.
exit status 1
```
make error:
```
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1
exit status 2
```

**Comment by DynamicSquid** [comment]
For g++ and clang, make sure you add the `-std=c++17` so `std::variant` will be defined. I will update the README to reflect that.

For the Makefile, I'm not sure why it's not working. I'll try looking into that. What OS are you using?

Also, I there are binaries (I'm not sure what version though) for Windows and Linux on the website, so you can also download those for a quick way to use Night.

Thanks for the report!

**Comment by DynamicSquid** [comment]
Fixed!

You can use CMake and g++7 to build Night like so:

```
git clone https://github.com/DynamicSquid/night.git
cd night

mkdir build
cd build

cmake -G "MinGW Makefiles" ../
cmake --build .
```

I'll resolve this issue once I update the README and websites docs. Thanks for the report!

**Comment by RowanFromBJC** [comment]
Nice, although on some systems you will have to use `cmake -G "Unix Makefiles" ../`

**Comment by alexapostolu** [comment]
Yup, I've update the Readme to state the Unix Makefiles for Linux, thanks!
