### ISSUE TITLE
Do you have an FAQ?

### ISSUE THREAD

**Issue by RojjaCebolla** [DynamicSquid/night#73]
This language looks quite similar to C++, but I'm curious if you have any goals for it, that would help someone decide why to write in Night instead of C++?

**Comment by DynamicSquid** [comment]
It's no where close to C++ :)

It's more related to Python. In a couple weeks, I'll be done the first stable version, and I'll have also updated the README page and website. Also thanks for bringing that up, I'll make sure to include why code in Night over Python.
