### ISSUE TITLE
CI isn't working

### ISSUE THREAD

**Issue by DynamicSquid** [DynamicSquid/night#78]
The CI using Travis isn't working. I'm trying to use `cmake` to generate a `.elf` file for Linux.

**Comment by programmeruser2** [comment]
You may want to look at Travis CI's logs.
https://travis-ci.com/github/DynamicSquid/night/builds/219851490
It seems like there's a syntax error in `CMakeLists.txt`.

**Comment by DynamicSquid** [comment]
Perfect, thank you! So I fixed the `cmake` bug (and I saw the first green check mark in the CI in months 😮), but now there's another bug, not with the CI but with my language. I think I should be able to fix it sometime soon.

I'll keep this issue open just as a reminder.
