### ISSUE TITLE
Syscalls

### ISSUE THREAD

**Issue by programmeruser2** [DynamicSquid/night#79]
Is there anyway I could invoke syscalls within Night?
I think this would best suited for a library since syscalls are a Unix/Linux only feature.
It might be possible with a [foreign function interface](https://en.wikipedia.org/wiki/Foreign_function_interface).

**Comment by DynamicSquid** [comment]
Would an implementation using C++'s `system()` work?

**Comment by programmeruser2** [comment]
[Syscalls](https://en.wikipedia.org/wiki/System_call) are not the same as `system()`, which runs a shell command in a subshell.

**Comment by DynamicSquid** [comment]
How would I implement that? I'm thinking about the FFI, but I'm not sure where to get started. Is there a way to invoke syscalls in C++ using FFI?

**Comment by programmeruser2** [comment]
The FFI would probably just be an API that opens DLLs and runs functions from them. You would then put the syscall functions inside a DLL, probably written in C.

**Comment by DynamicSquid** [comment]
@programmeruser2 I'm still a little confuzzled on what you mean? Like here's how I currently implement predefined function calls:

```cpp
if (function_call.name == "input") {
  // do something
}
else if (function_call.name == "print") {
  // do something
}
```

It's not the best way, but I can't think of any other way to implement predefined functions.... So I could do the same for syscalls (except there's a lot of them):

```cpp
#include <sys/syscall.h>
#include <unistd.h> // I don't know which header to include?

if (function_call.name == "chdir") {
  // function parameters are already checked to be correct, so don't worry about that
  int err = chdir(function_call.args[0]);
  if (err == -1)
    throw Error();
}
```

Could you provide a code snippet of your way?

**Comment by programmeruser2** [comment]
First of all, you should probably store all functions, including built-ins, in a `std::unordered_map`. 
Second of all, you could create a `syscall()` function that you can pass parameters to, but that requires variable length arguments.
You have three choices here:
1. Implement a FFI API
2. Implement individual syscall functions
3. Implement `syscall()` and variable length arguments

**Comment by DynamicSquid** [comment]
@programmeruser2 actually I already use a map, I was just using if statements for the sake of simplicity. And sure, I'll give those a try, unless you want to create a PR yourself, but it's fine if you don't?

**Comment by DynamicSquid** [comment]
I'm actually going to hold this off for now. syscalls being not compatible with Windows is a problem at the moment. Maybe sometime later I'll implement a way.

**Comment by firefish111** [comment]
well you see, you could borrow me as your Linux tester

**Comment by DynamicSquid** [comment]
@firefish111 I have ways of testing it on Linux, it's just that I don't want some features of my language to be compatible to a certain OS. In the future once I add syntax that allows the user to check OS compatibility, then I'll add it.

**Comment by programmeruser2** [comment]
There should be a way to create OS specific releases, like how gcc does it.

**Comment by firefish111** [comment]
GCC has no Windows release, unless you mean mingw

**Comment by firefish111** [comment]
CLang however has a release on all platforms.
