### ISSUE TITLE
Having trouble installing and running Night

### ISSUE THREAD

**Issue by BD103** [DynamicSquid/night#80]
I followed the tutorial on the GH Pages and installed with Replit. It still doesn't recognize the command `night`, and I cannot run any files. Any advice?

**Comment by RowanFromBJC** [comment]
After building, in the shell tab, run these commands.
```bash
night_install_check() { read -p "REPL name: " name && cd && cd $name && cd night/build && export PATH="$(pwd):$PATH" && echo "Now it works, if it says command not found, run these commands again."; }
echo $PATH | grep "night/build" || night_install_check
```
When it asks for your repl name, use the repl name that shows up in the shell tab (without the ~/)

**Comment by RowanFromBJC** [comment]
This is just for Replit, not other devices

**Comment by BD103** [comment]
Thank you, I'll try it out.

**Comment by DynamicSquid** [comment]
Hi @BD103, Replit uses Linux. You can still follow my tutorial, but the only different is you have to do `./night` instead of `night`. I'll update my tutorial. Thanks !

**Comment by BD103** [comment]
Thank you!
