### ISSUE TITLE
Website is not responsive and needs improvement

### ISSUE THREAD

**Issue by IronManCool001** [DynamicSquid/night#82]
![Screenshot_20210508-232408](https://user-images.githubusercontent.com/63513685/117548800-8fb9ec00-b054-11eb-9d93-d20b548657a5.png)
Website is not responsive and needs CSS fix

**Comment by AntimatterReactor** [comment]
Yeah, I've fixed that, but unfortunately DynamicSquid doesn't accept the css and js part, so nothing's changed

**Comment by DynamicSquid** [comment]
I'm not really good with responsive design, but I definitely have that on my mind. PRs are welcome too :)

Also @AntimatterReactor, you just removed some JS, but it didn't change the responsiveness

**Comment by AntimatterReactor** [comment]
yeah, that one just cause the background gradient cause so much lag that my decent computer can't deal with it, so i'm forced to remove it @DynamicSquid. Also, it did makes a difference.

**Comment by DynamicSquid** [comment]
> 
> 
> yeah, that one just cause the background gradient cause so much lag that my decent computer can't deal with it, so i'm forced to remove it @DynamicSquid. Also, it did makes a difference.

It doesn't cause quite as much lag on much computer, but I'm definitely going to use native JS or perhaps change the algorithm

**Comment by AntimatterReactor** [comment]
> 
> 
> > yeah, that one just cause the background gradient cause so much lag that my decent computer can't deal with it, so i'm forced to remove it @DynamicSquid. Also, it did makes a difference.
> 
> It doesn't cause quite as much lag on much computer, but I'm definitely going to use native JS or perhaps change the algorithm

Well, I hope so

**Comment by DynamicSquid** [comment]
Which link?

**Comment by IronManCool001** [comment]
I made the buttons responsive, view this pull request: https://github.com/DynamicSquid/night/pull/83

**Comment by AntimatterReactor** [comment]
> 
> 
> Which link?

nvm

**Comment by AntimatterReactor** [comment]
How come have this not been solved yet @DynamicSquid ? It's been 6 months...

**Comment by StringentDev** [comment]
@DynamicSquid Yeah... it seems to not be very performant on my device as I get lag whilst scrolling.
