### ISSUE TITLE
Current build is 100% uncompilable

### ISSUE THREAD

**Issue by AntimatterReactor** [DynamicSquid/night#84]
Except if that's what was meant by "unstable build"
Then i suggest to close this issue and says so in readme.

pls

**Comment by firefish111** [comment]
I clicked on this email going for something worth reading, like @whippingdot roasting @headiscoding again

**Comment by AntimatterReactor** [comment]
lol

**Comment by whippingdot** [comment]
Don't ping me randomly @firefish111

**Comment by firefish111** [comment]
no u

**Comment by firefish111** [comment]
waiter you actually received it? wops

**Comment by DynamicSquid** [comment]
Currently working on a stable version, it'll be out < 2 weeks :)

And for the rest of you don't spam

**Comment by AntimatterReactor** [comment]
ok, cool

**Comment by headiscoding** [comment]
> I clicked on this email going for something worth reading, like @whippingdot roasting @headiscoding again

😭

**Comment by alexapostolu** [comment]
It is 100% compilable now
