### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by IronManCool001** [DynamicSquid/night#85]
![image](https://user-images.githubusercontent.com/63513685/128967511-d02f7ff7-a5aa-4002-a4eb-380e2a94a549.png)
**Guys the website seems broken see the above image**

**Comment by EpicGamer007** [comment]
night isn't supposed to be this bright lol

**Comment by DynamicSquid** [comment]
lol yes, it's currently under changes. I'll add a note in the readme

**Comment by alexapostolu** [comment]
Fixed!
