### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by IronManCool001** [DynamicSquid/night#86]
<samp>
In file included from src/lib/error.h:3,
                 from src/night.cpp:3:
src/lib/./string.h:271:62: error: 'night::string operator""_s(const char*, unsigned int)' has invalid argument list
  night::string operator""_s(const char* str, unsigned int len)
                                                              ^
In file included from src/night.cpp:3:
src/lib/error.h: In constructor 'Error::Error(const night::string&, const night::array<Token>&, int, int, const night::string&)':
src/lib/error.h:41:21: error: unable to find string literal operator 'operator""_s' with 'const char [2]', 'long long unsigned int' arguments
     code[a].value = "'"_s + code[a].value + "'";
                     ^~~~~
src/lib/error.h:43:21: error: unable to find string literal operator 'operator""_s' with 'const char [2]', 'long long unsigned int' arguments
     code[a].value = "\""_s + code[a].value + "\"";
                     ^~~~~~
src/lib/error.h: In member function 'night::string Error::what() const':
src/lib/error.h:51:21: error: unable to find string literal operator 'operator""_s' with 'const char [9]', 'long long unsigned int' arguments
   output += I_RED + "Error - "_s + RESET;
                     ^~~~~~~~~~~~
src/lib/error.h:52:33: error: unable to find string literal operator 'operator""_s' with 'const char [3]', 'long long unsigned int' arguments
   output += U_RED + errorType + "\n\n"_s + RESET;
                                 ^~~~~~~~
In file included from src/file_extraction.h:11,
                 from src/night.cpp:4:
src/./lexer.h: In function 'night::array<Token> Lexer(const night::string&)':
src/./lexer.h:326:89: error: unable to find string literal operator 'operator""_s' with 'const char [7]', 'long long unsigned int' arguments
   throw Error(night::_invalid_token_, tokens, tokens.length() - 1, tokens.length() - 1, "token "_s + token + "' is not a valid token"_s);
                                                                                         ^~~~~~~~~~
src/./lexer.h:326:110: error: unable to find string literal operator 'operator""_s' with 'const char [23]', 'long long unsigned int' arguments
   throw Error(night::_invalid_token_, tokens, tokens.length() - 1, tokens.length() - 1, "token "_s + token + "' is not a valid token"_s);
                                                                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/interpreter/interpreter.h:12,
                 from src/file_extraction.h:13,
                 from src/night.cpp:4:
src/interpreter/./expr_parser.h: In function 'void EvaluateNumeric(night::array<Token>&, int, const night::string&)':
src/interpreter/./expr_parser.h:62:72: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
   throw Error(night::_invalid_expression_, expr, index - 1, index + 1, "operator '"_s + op + "' can only be used on values of type 'int' or 'dec', or if one of the values is of type 'str'");
                                                                        ^~~~~~~~~~~~~~
In file included from src/interpreter/interpreter.h:12,
                 from src/file_extraction.h:13,
                 from src/night.cpp:4:
src/interpreter/./expr_parser.h: In function 'void EvaluateNumComparison(night::array<Token>&, int, const night::string&)':
src/interpreter/./expr_parser.h:81:72: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
   throw Error(night::_invalid_expression_, expr, index - 1, index + 1, "operator '"_s + op + "' can only be used on values of type 'int' or 'dec'");
                                                                        ^~~~~~~~~~~~~~
src/interpreter/./expr_parser.h: In function 'void EvaluateComparison(night::array<Token>&, int, const night::string&)':
src/interpreter/./expr_parser.h:91:4: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
    "operator '"_s + op + "' can only compare to values of the same type");
    ^~~~~~~~~~~~~~
src/interpreter/./expr_parser.h:94:72: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
   throw Error(night::_invalid_expression_, expr, index - 1, index - 1, "operator '"_s + op + "' can only compare values of type 'bit', 'syb', 'int', 'dec', or 'str'");
                                                                        ^~~~~~~~~~~~~~
src/interpreter/./expr_parser.h:97:72: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
   throw Error(night::_invalid_expression_, expr, index + 1, index + 1, "operator '"_s + op + "' can only compare values of type 'bit', 'syb', 'int', 'dec', or 'str'");
                                                                        ^~~~~~~~~~~~~~
src/interpreter/./expr_parser.h: In function 'void EvaluateBoolean(night::array<Token>&, int, const night::string&)':
src/interpreter/./expr_parser.h:118:72: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
   throw Error(night::_invalid_expression_, expr, index - 1, index + 1, "operator '"_s + op + "' can only be used on values of type 'bit'");
                                                                        ^~~~~~~~~~~~~~
src/interpreter/./expr_parser.h: In function 'Token ParseExpression(night::array<Token>, night::array<Variable>&, night::array<Function>&, night::array<Array>&)':
src/interpreter/./expr_parser.h:246:71: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
        throw Error(night::_invalid_function_, expr, 0, expr.length(), "expecting "_s + night::itos(function->params.length()) + " parameters");
                                                                       ^~~~~~~~~~~~~~
src/interpreter/./expr_parser.h:328:63: error: unable to find string literal operator 'operator""_s' with 'const char [60]', 'long long unsigned int' arguments
       throw Error(night::_invalid_array_, expr, a + 3, b - 1, "array index is out of range; the last element is at index '"_s + night::itos(array->elems.length() - 1) + "'");
                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/file_extraction.h:13,
                 from src/night.cpp:4:
src/interpreter/interpreter.h: In function 'void Interpreter(night::array<night::array<Token> >&)':
src/interpreter/interpreter.h:141:79: error: unable to find string literal operator 'operator""_s' with 'const char [19]', 'long long unsigned int' arguments
      throw Error(night::_invalid_variable_, code[a], 2, code[a].length() - 2, "variable of type '"_s + night::ttos(variable->type) + "' cannot be assigned with expression of type '" + night::ttos(expression.type) + "'");
                                                                               ^~~~~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:173:61: error: unable to find string literal operator 'operator""_s' with 'const char [19]', 'long long unsigned int' arguments
       throw Error(night::_invalid_variable_, code[a], 1, 1, "variable of type '"_s + night::ttos(variable->type) + "' cannot be used with a '" + code[a][1].value + "' operator");
                                                             ^~~~~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:193:57: error: unable to find string literal operator 'operator""_s' with 'const char [24]', 'long long unsigned int' arguments
      throw Error(night::_invalid_array_, code[a], 2, 2, "array must be of type '"_s + night::ttos(array->type) + "'");
                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:229:58: error: unable to find string literal operator 'operator""_s' with 'const char [16]', 'long long unsigned int' arguments
       throw Error(night::_invalid_array_, code[a], b, b, "array of type '"_s + night::ttos(array->type) + "' cannot be assigned to array of type '" + night::ttos(evaluateElement.type) + "'");
                                                          ^~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:350:76: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
       throw Error(night::_invalid_function_, code[a], 0, code[a].length(), "expecting "_s + night::itos(function->params.length()) + " parameters");
                                                                            ^~~~~~~~~~~~~~
src/interpreter/interpreter.h:387:74: error: unable to find string literal operator 'operator""_s' with 'const char [11]', 'long long unsigned int' arguments
     throw Error(night::_invalid_function_, code[a], 0, code[a].length(), "expecting "_s + night::itos(function->params.length()) + " parameters");
                                                                          ^~~~~~~~~~~~~~
src/interpreter/interpreter.h:465:85: error: unable to find string literal operator 'operator""_s' with 'const char [16]', 'long long unsigned int' arguments
      throw Error(night::_invalid_array_, code[a], closeSquare + 3, closeSquare + 3, "array of type '"_s + night::ttos(code[a][0].type) + "' cannot be initialized with an array of type '" + night::ttos(assignArray->type) + "'");
                                                                                     ^~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:499:87: error: unable to find string literal operator 'operator""_s' with 'const char [38]', 'long long unsigned int' arguments
       throw Error(night::_invalid_array_, code[a], closeSquare, code[a].length() - 1, "too many elements in array; expected "_s + night::itos(arrayLength) + " elements");
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:549:66: error: unable to find string literal operator 'operator""_s' with 'const char [60]', 'long long unsigned int' arguments
     throw Error(night::_invalid_array_, code[a], 2, closeSquare, "array index is out of range; the last element is at index '"_s + night::itos(array->elems.length() - 1) + "'");
                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:553:89: error: unable to find string literal operator 'operator""_s' with 'const char [54]', 'long long unsigned int' arguments
     throw Error(night::_invalid_array_, code[a], closeSquare + 2, code[a].length() - 2, "array can only be assigned to an expression of type '"_s + night::ttos(array->type) + "'");
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/interpreter/interpreter.h:596:69: error: unable to find string literal operator 'operator""_s' with 'const char [60]', 'long long unsigned int' arguments
          throw Error(night::_invalid_array_, code[a], b + 3, c - 1, "array index is out of range; the last element is at index '"_s + night::itos(array->elems.length() - 1) + "'");
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [build_night] Error 1
</samp>

**Comment by AntimatterReactor** [comment]
Night is still on the making. Read #84

**Comment by AntimatterReactor** [comment]
note that the last stable build is commit 8079fa9e05499b97d60b8777a6aeb733c23dffb3

**Comment by IronManCool001** [comment]
Ok that solved my issue now you should close this issue plus I would like to recommend a discord server were you could list your programming language https://discord.gg/9PcQkaVpYv

**Comment by alexapostolu** [comment]
Fixed!
