### ISSUE TITLE
Night cannot compile on debian based linux distros

### ISSUE THREAD

**Issue by AntimatterReactor** [DynamicSquid/night#88]
Note: this probably has to do with debian based distros using gcc 9.3.0 instead of the newer gcc 11.1.0

**Comment by DynamicSquid** [comment]
Hmm, I thought you needed at least gcc8. Could you screenshot the error message you're getting?

**Comment by AntimatterReactor** [comment]
https://github.com/AntimatterReactor/night/runs/3528955169
that's the failed cmake build on github action (my fork btw)

**Comment by AntimatterReactor** [comment]
and this
![image](https://user-images.githubusercontent.com/63902100/132792422-22f9b7a0-8ce9-4a8c-90e5-fbe13e7fcd2c.png)

**Comment by DynamicSquid** [comment]
yeah, I think you need to update the gcc version since it doesn't recognize c++20 `std::ranges`. What's the highest version you can get?

**Comment by AntimatterReactor** [comment]
it works on gcc 10.3.0
![image](https://user-images.githubusercontent.com/63902100/132933829-3975a48c-6402-4ae7-b4c3-18be8008c479.png)

**Comment by DynamicSquid** [comment]
oh, perfect! I've already updated the readme to inform people to have a minimum gcc version of 10. I'll also fix those warnings

thanks!
