### ISSUE TITLE
[ENHANCEMENT] Update release to access on Replit

### ISSUE THREAD

**Issue by JBYT27** [DynamicSquid/night#95]
Hiya!

## About
I found this [Repl](https://replit.com/@DynamicSquid/night-template) that allowed Replit Users to use (pretty much any lang that had a release) custom langs. However, the current release seems (very) outdated, and I would like to ask if any of the devs could make a new release that includes all the current code? That way, we can access the current version on Replit (I'm testing with it to test my own lang as well :P). Thanks!

## Question
So just to clarify, the question was if you could release a release that holds all the current code :)

**Comment by CodeLongAndProsper90** [comment]
Doesn't replit support Nix?  So you could just merge this into nixpkgs then do a `nix-shell` invocation...

**Comment by JBYT27** [comment]
Well, yes, I tried that, but it doesn’t seem to work from what I did…
 
But I’ll try that again and see if it works

**Comment by DynamicSquid** [comment]
The current code might not work :/

That repl downloads the latest release (which does work)

**Comment by JBYT27** [comment]
Okay! Quick question, could you make a README that holds the syntax for that night version? 

So the current version is still a wip?

**Comment by JBYT27** [comment]
@CodeLongAndProsper90 - so I have a question: I tried using Nix (using DynamicSquid's repl fork), but I didn't know how to start the file, and I got stumped on running the file. Could you help with this?

> Repl source code: https://replit.com/@JBloves27/Nix-Night#source.night

**Comment by DynamicSquid** [comment]
@JBYT27 Some syntax is in the website https://dynamicsquid.github.io/night/ it's still in development

To run Night on Linux, follow the Linux instructions in the Readme. Once you built the project, you should see a ./night folder somewhere, and you can run that

**Comment by JBYT27** [comment]
Oh okay! Thank you!

i’ll try that and see if its up-to-daye and works (it prob will as u said tho)
